agvoy-app/src/Entity/Room.php
<?php

namespace App\Entity;

use App\Repository\RoomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RoomRepository::class)
 */
class Room
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Summary;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $capacity;

    /**
     * @ORM\Column(type="float")
     */
    private $superficy;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\ManyToOne(targetEntity=Owner::class, inversedBy="Owner_room")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    /**
     * @ORM\ManyToMany(targetEntity=Region::class, inversedBy="rooms")
     */
    private $Room_Region;

    /**
     * @ORM\ManyToMany(targetEntity=Indisponibilite::class, mappedBy="room")
     */
    private $indisponibilites;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="room")
     */
    private $reservations;

    public function __construct()
    {
        $this->Room_Region = new ArrayCollection();
        $this->indisponibilites = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSummary(): ?string
    {
        return $this->Summary;
    }

    public function setSummary(?string $Summary): self
    {
        $this->Summary = $Summary;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getSuperficy(): ?float
    {
        return $this->superficy;
    }

    public function setSuperficy(float $superficy): self
    {
        $this->superficy = $superficy;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getOwner(): ?Owner
    {
        return $this->owner;
    }

    public function setOwner(?Owner $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @return Collection|Region[]
     */
    public function getRoomRegion(): Collection
    {
        return $this->Room_Region;
    }

    public function addRoomRegion(Region $roomRegion): self
    {
        if (!$this->Room_Region->contains($roomRegion)) {
            $this->Room_Region[] = $roomRegion;
        }

        return $this;
    }

    public function removeRoomRegion(Region $roomRegion): self
    {
        $this->Room_Region->removeElement($roomRegion);

        return $this;
    }

    /**
     * @return Collection|Indisponibilite[]
     */
    public function getIndisponibilites(): Collection
    {
        return $this->indisponibilites;
    }

    public function addIndisponibilite(Indisponibilite $indisponibilite): self
    {
        if (!$this->indisponibilites->contains($indisponibilite)) {
            $this->indisponibilites[] = $indisponibilite;
            $indisponibilite->addRoom($this);
        }

        return $this;
    }

    public function removeIndisponibilite(Indisponibilite $indisponibilite): self
    {
        if ($this->indisponibilites->removeElement($indisponibilite)) {
            $indisponibilite->removeRoom($this);
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setRoom($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getRoom() === $this) {
                $reservation->setRoom(null);
            }
        }

        return $this;
    }
    
    public function __toString() {
        return (string) $this->getId();
    }
}

agvoy-app/templates/Nouscontacter.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Nous contacter</h1>
                    <p class="lead fw-normal text-white-50 mb-0"></p>
                </div>
            </div>
        </header>
        <br>
<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Accueil</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Nous contacter</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header bg-primary text-white"><i class="fa fa-envelope"></i> Contact
                </div>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <label for="name">Nom</label>
                            <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Entrez votre nom" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Adresse mail</label>
                            <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Entrez votre adresse mail" required>
                            <small id="emailHelp" class="form-text text-muted">Nous ne partagerons jamais votre e-mail avec quelqu'un d'autre</small>
                        </div>
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea class="form-control" id="message" rows="6" required></textarea>
                        </div>
                        <div class="mx-auto">
                        <button type="submit" class="btn btn-primary text-right">Envoyer</button></div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-4">
            <div class="card bg-light mb-3">
                <div class="card-header bg-success text-white text-uppercase"><i class="fa fa-home"></i> Notre adresse</div>
                <div class="card-body">
                    <p>5 rue Charles Fourier</p>
                    <p>91000 EVRY</p>
                    <p>France</p>
                    <p>Email : contact@c&c.com</p>
                    <p>Tel. +33 12 56 11 51 84</p>

                </div>

            </div>
        </div>
    </div>
</div>
<br>



{% endblock body %}

agvoy-app/templates/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

agvoy-app/templates/accueil.html.twig
{% extends 'base.html.twig' %}



{% block body %}

<!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Couettes & Café</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Le site de réservation par excellence</p>
                </div>
            </div>
        </header>
        <br>
        <br>
<style>
p {margin : 10px 20px 20px 40px}
</style>
 <p class="font-weight-light" >Couettes & Café est un site français qui propose des hébergements dans différents types de propriétés allant de l'hôtel au gîte touristique en passant par l'appartement. Vous pouvez vous inscrire ou vous connecter si vous êtes déjà client et regarder les annonces que l'on vous propose dans la rubrique "Annonces". </p>
 <center>
 <p class="font-weight-light">Réserver un logement n'a jamais été aussi simple ! </p>              
        
        
        <br>               
       <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="https://www.shbarcelona.fr/blog/fr/wp-content/uploads/2016/03/appartement-photo.jpg" class="d-block w-50" alt="photo1">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="https://www.marsinstyle.com/photo/gal/pic/gal-2245507.jpg?v=1378292141" class="d-block w-50" alt="photo2">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://www.madamedecore.com/ckfinder/userfiles/images/Appartement-industriel-loft-madame-decore-les-curieuses-paris-salon.jpg.jpg" class="d-block w-50" alt="photo3">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
        <br>
      
      
       <a class="btn btn-dark" href="/Contact" role="button">Nous contacter</a>
       <br>
<br>
        

{% endblock %} 

agvoy-app/templates/annonces.html.twig
{% extends 'base.html.twig' %}

 {% block body %}
 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}C&C{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            <!-- Core theme CSS (includes Bootstrap)-->
            <link href="/startbootstrap-shop-homepage-gh-pages/css/styles.css" rel="stylesheet">
            <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
            <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Core theme JS-->
            <script src="{{ asset('js/scripts.js') }}"></script>
        {% endblock %} {# javascripts #}
    </head>
    <body>
       
    

        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Annonces</h1>
                    <p class="lead fw-normal text-white-50 mb-0"></p>
                </div>
            </div>
        </header>
        
       

        {% for region in regions %}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
  
  
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        {{region.name}}
      </button>
    </h2>
    
    
    {% for room in rooms%}
    {% for region_ in room.RoomRegion%}
    {% if region_ == region.name %}
    
    <div id="collapseOne" class="accordion-collapse collapse " aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">      
      <div class="card" style="width: 18rem;">
  <img src="https://www.vivons-maison.com/sites/default/files/styles/740px/public/field/image/appartement-de-ville-interieur-design.jpg?itok=Qo-ErhjU" class="card-img-top" alt="image">
  <div class="card-body">
    <h5 class="card-title">{{ room.summary }}</h5>
    <p class="card-text"> {{ room.description }}</p>
    <a href="{{path('reservationid' , {'id' : room.id}) }}" type="button" class="btn btn-primary">Reserver</a>
  </div>
</div>
    </div>
    </div>
    {% endif %}
    {% endfor %}{% endfor %}
  </div>

  {% endfor %}
        

  
  
  </html>
 {% endblock %}

agvoy-app/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}C&C{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            <!-- Core theme CSS (includes Bootstrap)-->
            <link href="/startbootstrap-shop-homepage-gh-pages/css/styles.css" rel="stylesheet">
            <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
            
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
            <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Core theme JS-->
            <script src="{{ asset('js/scripts.js') }}"></script>
        {% endblock %} {# javascripts #}
    </head>
    
    
    
    
    <body>
        
 <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-white bg-white">
       <div class="container">
          <a class="navbar-brand" href="{{ path('home') }}">C&C</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {{ render_bootstrap_menu('main') }}
             </ul>
          </div>
        </div>
     </nav>
        
        
        
        
        {% block body %} {% endblock body %}
        
        
        
 
             <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Rali Benjelloun / Maxence Durieu 2021</p></div>
        </footer>
       
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

agvoy-app/templates/connexion.html.twig
{% extends 'base.html.twig' %}

 {% block body %}
 
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="css/style.css">

    <link rel="icon" href="Favicon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

</head>
<body>

<br>

<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Connexion</div>
                    <div class="card-body">
                        <form action="" method="">
                            <div class="form-group row">
                                <label for="email_address" class="col-md-4 col-form-label text-md-right">Addresse mail</label>
                                <div class="col-md-6">
                                    <input type="text" id="email_address" class="form-control" name="email-address" required autofocus>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="Mot de passe" class="col-md-4 col-form-label text-md-right">Mot de passe</label>
                                <div class="col-md-6">
                                    <input type="Mot de passe" id="Mot de passe" class="form-control" name="Mot de passe" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember"> Se rappeler de moi
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Connexion
                                </button>
                                <a href="#" class="btn btn-link">
                                    Mot de passe oublié ?
                                </a>
                            </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>

</main>
</body>
</html>
<br>
 <br>
 {% endblock %}

agvoy-app/templates/inscription.html.twig
{% extends 'base.html.twig' %}

 {% block body %}
 
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
<br>

<div class="container">


<div class="row justify-content-center">
<div class="col-md-6">
<div class="card">
<header class="card-header">
	<a href="/Connexion" class="float-right btn btn-outline-primary mt-1">Se Connecter</a>
	<h4 class="card-title mt-2">S'inscrire</h4>
</header>
<article class="card-body">



<form href="{{ path('inscription')}} , method='post'">
	<div class="form-row">
		<div class="col form-group">
			<label>Prenom </label>   
		  	<input name='prenom' type="text" class="form-control" placeholder="Entrez votre prénom">
		</div> <!-- form-group end.// -->
		<div class="col form-group">
			<label>Nom</label>
		  	<input name='nom'type="text" class="form-control" placeholder="Entrez votre nom">
		</div> <!-- form-group end.// -->
	</div> <!-- form-row end.// -->
	<div class="form-group">
		<label>Adresse mail</label>
		<input name='email 'type="email" class="form-control" placeholder="">
	</div> <!-- form-group end.// -->
	<div class="form-group">
			
	</div> <!-- form-group end.// -->
	<div class="form-row">
		<div class="form-group col-md-6">
		</div> <!-- form-group end.// -->
		
	</div> <!-- form-row.// -->
	<div class="form-group">
		<label>Mot de Passe</label>
	    <input name='mdp'class="form-control" type="password">
	</div> <!-- form-group end.// -->  
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block"> S'inscrire  </button>
    </div> <!-- form-group// -->      
    <small class="text-muted">En cliquant sur le bouton « S'inscrire », vous confirmez que vous acceptez <br>nos conditions d'utilisation et notre politique de confidentialité.</small>                                          
</form>

</article> <!-- card-body end .// -->
<div class="border-top card-body text-center">Vous avez déjà un compte ? <a href="/Connexion">Se connecter</a></div>
</div> <!-- card.// -->
</div> <!-- col.//-->

</div> <!-- row.//-->


</div> 
<!--container end.//-->
<br>
 <br>
 {% endblock %}

agvoy-app/templates/nouvellereservation.html.twig
{% extends 'base.html.twig' %}



{% block body %}

Encore à construire : formulaire
<br>

 id de la room :{{roomid}}        

{% endblock %} 